# -*- coding: utf-8 -*-
"""Projeto_ETL_DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zk6upmFpSZmOmCCnxEP_r4sV7FJoCvMM

Importando Base de dados
"""

import pandas as pd
dados = pd.read_csv('aluguel.csv', sep=';')

"""Usarei o comando head no DataFrame para ter o primeiro contato com ele"""

dados.head(5)

"""Não consigo ter uma vizualização de todos os tipos de imoveis, logo vou fazer uma extração para fazer outra vizualizção."""

dados['Tipo']

"""Vou criar uma variavel para armazenar os tipos de imoveis e usarei o drop_duplicates para ficar com os valores unicos."""

tipo_de_imovel = list(dados['Tipo'].drop_duplicates())

tipo_de_imovel

"""#### Vou criar um DataFrame separado, só com os dados dos tipos imoveis Solicitados."""

comercial = ['Conjunto Comercial/Sala',
'Loja/Salão',
'Casa Comercial',
'Loja Shopping/ Ct Comercial',
]

selecao = dados['Tipo'].isin(comercial)

dados_comercial = dados[selecao]

dados_comercial

"""Vamos comparar o numero de linhas dos dois DataFrames, para ver se a separação funcionou."""

dados.shape

dados_comercial.shape

"""O index do nosso DataFrame Comercial está bagunçado, logo vamos organizar ele"""

dados_comercial.index

"""Usando a função range para percorrer o dataFrame e renumerar eles, e o shape[0] é usado so para percorrer as linhas

"""

dados_comercial.index = range(dados_comercial.shape[0])

dados_comercial

"""Observando o DataFrame vemos alguns valores NaN em algumas colunas, vamos detectar a quantidade desses valores."""

dados_comercial[dados_comercial['Condominio'].isnull()].shape[0]

dados_comercial[dados_comercial['IPTU'].isnull()].shape[0]

"""As colunas IPTU e Condominio tem uma quantitade relevante de valores faltantes, assim irei alocar o valor zero nessas linhas NaN.
OBS: Na colunar Valor existem 8 valores faltantes, como a quantitade é muito pequena em comparacao ao DataFrame irei dropar esses valores.

"""

dados_comercial = dados_comercial.dropna(subset=['Valor'])

"""Agora sem Valores NaN na coluna Valor.

"""

dados_comercial[dados_comercial['Valor'].isnull()].shape[0]

dados_comercial = dados_comercial.fillna({'Condominio': 0, 'IPTU': 0})

dados_comercial[dados_comercial['Condominio'].isnull()].shape[0]

dados_comercial[dados_comercial['IPTU'].isnull()].shape[0]

"""## Definindo a quantitade de cada tipo de imovel"""

selecao_comercial_sala = dados_comercial['Tipo'] == 'Conjunto Comercial/Sala'
quantidade_comercial_sala = dados_comercial[selecao_comercial_sala].shape[0]
quantidade_comercial_sala

selecao_loja_salão = dados_comercial['Tipo'] == 'Loja/Salão'
quantidade_loja_salão = dados_comercial[selecao_loja_salão].shape[0]
quantidade_loja_salão

selecao_casa_comercial = dados_comercial['Tipo'] == 'Casa Comercial'
quantidade_casa_comercial = dados_comercial[selecao_casa_comercial].shape[0]
quantidade_casa_comercial

selecao_loja_shopping_ct_comercial = dados_comercial['Tipo'] == 'Loja Shopping/ Ct Comercial'
quantidade_loja_shopping_ct_comercial = dados_comercial[selecao_loja_shopping_ct_comercial].shape[0]
quantidade_loja_shopping_ct_comercial

print(f"Nº de imoveis classificados como tipo Conjunto Comercial/Sala são {quantidade_comercial_sala}")
print(f"Nº de imoveis classificados como tipo Loja/Salão são {quantidade_loja_salão}")
print(f"Nº de imoveis classificados como tipo Casa Comercial são {quantidade_casa_comercial}")
print(f"Nº de imoveis classificados como tipo Loja Shopping/ Ct Comercial são {quantidade_loja_shopping_ct_comercial}")
print(f"Nº Total de imoveis {dados_comercial.shape[0]}")

"""### Exportando a Nova Planilha."""

dados_comercial.to_csv('aluguel_comercial.csv', sep= ';', index=False)